### ISSUE TITLE
Move away from Buffer constructor

### ISSUE THREAD

**Issue by gabrielschulhof** [ipld/js-ipld-ethereum#26]
`new Buffer(...)` is deprecated and unsafe. Would it be possible to move the [instances](https://github.com/ipld/js-ipld-ethereum/search?q=%22new+Buffer%22&unscoped_q=%22new+Buffer%22) of its usage to `Buffer.from(...)`?

**Comment by vmx** [comment]
@gabrielschulhof Sorry for the delay. It makes sense to move to `Buffer.from(...)`. If you could help with doing a Pull Request that would be great.

**Comment by vmx** [comment]
That's fixed on master.
