### ISSUE TITLE
Do we still need all the other repo and modules? 

### ISSUE THREAD

**Issue by diasdavid** [ipld/js-ipld-ethereum#4]
There are a ton of repos right now https://github.com/ipld?utf8=%E2%9C%93&q=js-ipld-eth&type=&language=

I believe these were all coalesced into this one. Can we delete/deprecate all the others? @kumavis ?

**Comment by diasdavid** [comment]
Seems this wasn't the first time I thought of this https://github.com/ipld/js-ipld-eth-star/issues/2 :)

**Comment by diasdavid** [comment]
I don't have publish perms on ipld-eth-star and so I couldn't deprecate it. Mind adding me or doing that? Thanks!

**Comment by diasdavid** [comment]
Ok, just went and updated all the repos, published this module and added you as an owner. Now we just need to get all the other packages deprecated on npm. Can you handle that @kumavis ?

**Comment by kumavis** [comment]
deprecated the old modules and verified they have a deprecation warning on the readme (added a missing one)
also deprecated ipld-eth-star

**Comment by kumavis** [comment]
how long to keep the deprecated repos around is up to you
you could transfer them to my name if you want to clean up `ipld` org
