### ISSUE TITLE
Is there any documentation yet?

### ISSUE THREAD

**Issue by ads1018** [ipld/js-ipld-ethereum#6]
I've heard such great things about this project and would like to try it out for an Ethereum dapp I'm building but I don't know where to start. Is there an documentation yet which you could point me to?

**Comment by kumavis** [comment]
This is fairly low-level stuff. ipld style deserialization of ethereum blocks and transactions. if you're looking for a browser light client with drop-in `provider` obj (like `new Web3(lightclient.provider)`), we're not there yet.

**Comment by kumavis** [comment]
If you do have a question about the low level stuff, let me know

**Comment by sunny-g** [comment]
@kumavis I've got a quick question: the `binaryBlob`s that the `resolve` and `deserialize` functions take in - are those raw binary blobs of Ethereum objects? As in, the same objects that the Ethereum network passes around and/or stores? And are these stored as-is IPFS (no conversion to CBOR, etc)? I'm trying to do the same thing as this library (I think) for the Stellar blockchain which checkpoints blockchain state in XDR. 

Any guidance would be appreciated, thanks!

**Comment by vmx** [comment]
@sunny-g: That's correct. The `binaryBlobs` are raw Ethereum blocks. You could do the same thing for other blockchains. If you want to create your own IPLD format implementation, you can also have a look at https://github.com/ipld/js-ipld-bitcoin which I've created recently. Its codebase is a bit simpler than the Ethereum one. Feel free to ask question at https://github.com/ipld/interface-ipld-format/ if you want to implement your own format.
